### ISSUE TITLE
MonetaryAmountType should respect fractions digits when persisting to database

### ISSUE THREAD

**Issue by stwonary** [vladmihalcea/hypersistence-utils#498] opened 2022-10-17 14:21 UTC
Some country don't have any fraction digit. and when persisting should only store the whole number.

I fixed it by explicitly set the scale on `getPropertyValue` on https://github.com/vladmihalcea/hibernate-types/blob/7b022294534a9a109cc4749fd7ab9affdfd21d59/hibernate-types-60/src/main/java/com/vladmihalcea/hibernate/type/money/MonetaryAmountType.java#L34

My fix:
```java
  @Override
  public Object getPropertyValue(MonetaryAmount component, int property) throws HibernateException {
    // alphabetical (amount, currency)
    switch (property) {
      case 0:
        return component
            .getNumber()
            .numberValue(BigDecimal.class)
            .setScale(
                component.getCurrency().getDefaultFractionDigits(),
                RoundingMode.HALF_UP
            );
      case 1:
        return component.getCurrency().getCurrencyCode();
    }
    return null;
  }
`

**Comment by vladmihalcea** [comment] 2022-10-17 14:23
The first step would be to provide a test case that proves the issue. Unless a generic fix could be provided, a configuration option could work as well.

**Comment by stwonary** [comment] 2022-10-17 15:09
Hi @vladmihalcea  thank you for your prompt reply.

I just added a test in my fork branch please check it out.  72fe63988dc274b9f52d0c8055aa10458fdfb14b

Here are some screenshot of the results 

Stored values:
![Screen Shot 2022-10-17 at 12 03 50 PM](https://user-images.githubusercontent.com/59780143/196213735-825483fa-0e14-4b82-b8b5-aec8951282b9.png)

Money value and BigDecimal value. 
![Screen Shot 2022-10-17 at 12 04 03 PM](https://user-images.githubusercontent.com/59780143/196213887-d84c567b-2de9-4f80-9f6a-57a057243618.png)

Failed test result:
![Screen Shot 2022-10-17 at 12 05 11 PM](https://user-images.githubusercontent.com/59780143/196213934-6fbf2224-ca7c-4105-9ee8-0ab6d597efa8.png)

**Comment by stwonary** [comment] 2022-10-17 15:51
@vladmihalcea please check my PR https://github.com/vladmihalcea/hibernate-types/pull/499

any feedback is very welcome.

**Comment by vladmihalcea** [comment] 2022-10-17 15:54
Thanks, I'll review it when I have some time.

**Comment by stwonary** [comment] 2022-10-17 18:51
I tried to implement for Hibernate 5.2 and Hibernate 5.5 without success.
For some reason on those versions the values returned by `getPropertyValue` are totally ignored. 


I hardcoded `BigDecimal.valueOf(1)` in `getPropertyValue`. The method is called but the valued persisted is still from the original `monetaryAmount.getNumber().numberValue(BigDecimal.class)` 

any ideas?

**Comment by vladmihalcea** [comment] 2022-10-17 18:53
@stwonary Don't worry about it. When I have some time, I'll take your integration test case and see if I can provide a fix for it. Hopefully, in November, I'll have some time to review it.

**Comment by vladmihalcea** [comment] 2022-12-16 11:47
I tried the PR, and I rebased it on [this branch](https://github.com/vladmihalcea/hibernate-types/tree/monetary-digits).

However, the `MySQLMonetaryAmountTypeTest` is failing:

```
java.lang.AssertionError: expected: org.javamoney.moneta.Money<PYG 123.00> but was: org.javamoney.moneta.Money<PYG 123.00>
Expected :org.javamoney.moneta.Money<PYG 123.00>
Actual   :org.javamoney.moneta.Money<PYG 123.00>
```

If you want to investigate it, then you can use that branch as a reference.

**Comment by vladmihalcea** [comment] 2023-03-26 12:48
Closed as the test case doesn't work and the problem is not clear at all.

**Closed by vladmihalcea** 2023-03-26 12:48 UTC
Labels: requires test case
