### ISSUE TITLE
"java.lang.NullPointerException ... because "this.enumType" is null" when using  Specification with a collection of enums on PostgreSQL

### ISSUE THREAD

**Issue by vprudnikov** [vladmihalcea/hypersistence-utils#630] opened 2023-05-26 13:57 UTC
Hi,

I have a problem (the demo is attached) when using `PostgreSQL`, `Spring Boot 3.1` and `hypersistence-utils-hibernate-62`:

Entity class:
```
@Entity
public class DemoEntity {
...

    @ElementCollection //this property leads to the problem
    private Set<DemoEnum> demoEnums = new HashSet<>();
...
```

When running the following test the `DemoTest`:
```
    @Test
    void demoTest() {
        var entity = repository.save(new DemoEntity());

        Specification<DemoEntity> spec = (root, query, builder) ->
                builder.isMember(DEMO, root.get("demoEnums"));

        assertThat(repository.findOne(spec).get().getId()).isEqualTo(entity.getId());
    }

```

The following exception occurs:
```
java.lang.NullPointerException: Cannot invoke "org.hibernate.type.EnumType.nullSafeSet(java.sql.PreparedStatement, java.lang.Enum, int, org.hibernate.engine.spi.SharedSessionContractImplementor)" because "this.enumType" is null

	at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.set(PostgreSQLEnumType.java:76)
	at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.set(PostgreSQLEnumType.java:32)
	at io.hypersistence.utils.hibernate.type.ImmutableType.nullSafeSet(ImmutableType.java:103)
	at org.hibernate.type.internal.UserTypeSqlTypeAdapter$ValueBinderImpl.bind(UserTypeSqlTypeAdapter.java:183)
	at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:117)
	at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:107)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.bindParameters(DeferredResultSetAccess.java:199)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:228)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:163)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:204)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:84)
	at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)
	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:65)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:198)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:362)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:109)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:302)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:243)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
	at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:473)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findOne(SimpleJpaRepository.java:458)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:288)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:163)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
	at jdk.proxy2/jdk.proxy2.$Proxy116.findOne(Unknown Source)
	at com.example.demo.DemoTest.demoTest(DemoTest.java:49)
```

**Note**: H2 database doesn't have that issue.

**A link to the demo project:**
[psql-enum-problem.zip](https://github.com/vladmihalcea/hypersistence-utils/files/11575895/psql-enum-problem.zip)

**Comment by vladmihalcea** [comment] 2023-05-26 15:41
@vprudnikov Try to debug the library and see what's needed to be done to get this issue fixed.

**Comment by vprudnikov** [comment] 2023-05-26 20:31
@vladmihalcea , is it possible for you to quickly check the demo? The thing is that I'm unaware of abstractions and the expected behavior? Maybe you will figure it out in a minute.

**Comment by vladmihalcea** [comment] 2023-05-27 05:55
@vprudnikov Check out [this test case](https://github.com/vladmihalcea/hypersistence-utils/blob/e3d8fa192dc872fc0ce7162fcc90a4b6b300ee0d/hypersistence-utils-hibernate-62/src/test/java/io/hypersistence/utils/hibernate/type/basic/PostgreSQLEnumTest.java#L73) that also bind a value that's mapped using `PostgreSQLEnumType`.

Having that test can help you understand why my test works while yours fail and see how you can work around it or provide a fix for your use case.

**Comment by vladmihalcea** [comment] 2023-05-28 12:03
Closed as the demo does not use any Type from this library.

**Closed by vladmihalcea** 2023-05-28 12:03 UTC
Labels: requires investigation

**Comment by vprudnikov** [comment] 2023-05-28 19:29
@vladmihalcea , sorry, I didn't get your point since your test checks a single enum property, not a collection of enums.

In other words, this doesn't help:
```
    @ElementCollection
    @Type(PostgreSQLEnumType.class)
    private Set<DemoEnum> demoEnums = new HashSet<>();
```

It leads to another problem:
````
Caused by: org.hibernate.MappingException: Error creating SQL create commands for table : demo_entity_demo_enums
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:104)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:41)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createTables(SchemaCreatorImpl.java:420)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createSequencesTablesConstraints(SchemaCreatorImpl.java:340)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:239)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:172)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:142)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:118)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:254)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
	at org.hibernate.boot.internal.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:37)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:291)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:431)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1455)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	... 97 common frames omitted
Caused by: org.hibernate.MappingException: Unable to determine SQL type name for column 'demo_enums' of table 'demo_entity_demo_enums'
	at org.hibernate.mapping.Column.getSqlTypeName(Column.java:281)
	at org.hibernate.mapping.Column.getSqlType(Column.java:339)
	at org.hibernate.tool.schema.internal.ColumnDefinitions.appendColumnDefinition(ColumnDefinitions.java:154)
	at org.hibernate.tool.schema.internal.ColumnDefinitions.appendColumn(ColumnDefinitions.java:88)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:73)
	... 116 common frames omitted
Caused by: org.hibernate.HibernateException: No type mapping for org.hibernate.type.SqlTypes code: 1111 (OTHER)
	at org.hibernate.type.descriptor.sql.spi.DdlTypeRegistry.getTypeName(DdlTypeRegistry.java:205)
	at org.hibernate.type.descriptor.sql.spi.DdlTypeRegistry.getTypeName(DdlTypeRegistry.java:184)
	at org.hibernate.mapping.Column.getSqlTypeName(Column.java:277)
```

As a temporary solution, I would like to switch off the type contribution for `PostgreSQLEnumType`, however, I can't find how to do that.

P.S. my demo project is very simple and can be run by typing `mvn package`.

**Comment by vladmihalcea** [comment] 2023-05-28 19:32
You don't need to create a demo project since there are hundreds of integration tests you could use as a template to replicate an issue.

The advantage of providing an integration test in the project is that it will prevent any future regressions.

**Comment by vprudnikov** [comment] 2023-05-28 19:39
@vladmihalcea what's your suggestion? create a new test in the `PostgreSQLEnumTest` ?

**Comment by vladmihalcea** [comment] 2023-05-28 19:49
In this case, it's not needed because the `PostgreSQLEnumType` is for basic entity properties only.

For collections, there are other types as explained in [the manual](https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#collection-type-ann), but Hypersistence Utils doesn't implement that use case.

**Comment by vprudnikov** [comment] 2023-05-28 19:54
@vladmihalcea I see. Is it possible to "switch it off" so Hypersistence Utils won't try using PostgreSQLEnumType with @ElementCollection?

**Comment by vladmihalcea** [comment] 2023-05-28 19:58
There's no switch. You will need to implement that Type yourself as explained in the Hibernate manual.

If you want to contribute it to the project, you will need to do it in all project modules.

**Comment by vprudnikov** [comment] 2023-05-28 20:00
I would say that the ability to switch it off would be a solution since it works without a dependency on Hypersistence Utils.

**Comment by vladmihalcea** [comment] 2023-05-28 20:02
If it works without a dependency on Hypersistence Utils, then why did you open an issue?

**Comment by vprudnikov** [comment] 2023-05-28 20:06
because I use Hypersistence Utils for different things like tsvector and others :)

**Comment by vladmihalcea** [comment] 2023-05-28 20:09
But, if you inspect the Exception stack trace, you'll see there's no Hypersistence Utils there, meaning that this project has nothing to do with your problem.

You should have reported on the Spring or Hibernate projects instead.

**Comment by vprudnikov** [comment] 2023-05-28 20:14
Please let me paste it again.

If the mapping looks like this:
    @ElementCollection
    private Set<DemoEnum> demoEnums = new HashSet<>();

Then the following error occurs:
```
java.lang.NullPointerException: Cannot invoke "org.hibernate.type.EnumType.nullSafeSet(java.sql.PreparedStatement, java.lang.Enum, int, org.hibernate.engine.spi.SharedSessionContractImplementor)" because "this.enumType" is null

	at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.set(PostgreSQLEnumType.java:76)
	at io.hypersistence.utils.hibernate.type.basic.PostgreSQLEnumType.set(PostgreSQLEnumType.java:32)
	at io.hypersistence.utils.hibernate.type.ImmutableType.nullSafeSet(ImmutableType.java:103)
```
... the rest of the stack trace is in the beginning of the issue.

If I do that:
    @ElementCollection
    @Type(PostgreSQLEnumType.class)
    private Set<DemoEnum> demoEnums = new HashSet<>();

then I get this: 
```
Caused by: org.hibernate.MappingException: Unable to determine SQL type name for column 'demo_enums' of table 'demo_entity_demo_enums'
```

... which is cause by Hypersistence Utils (I guess) since it creates (as I assume) a specific table for the mapping.

**Comment by vladmihalcea** [comment] 2023-05-28 20:38
Try removing [this line](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-62/src/main/java/io/hypersistence/utils/hibernate/type/HibernateTypesContributor.java#L62) and rebuild the project without it and see if it works.

**Comment by vprudnikov** [comment] 2023-05-28 20:44
@vladmihalcea , sure (I guess it will work).

By the way, I tried to add an ElementCollection to **your** test, and I implemented a new test there. It works in the following use case:
```
    @ElementCollection
    @Type(PostgreSQLEnumType.class)
    @Column(columnDefinition = "post_status_info")
    private Set<PostStatus> statuses = new HashSet<>();
```

However, it works JUST because the test explicitly defines a PostgreSQL type "post_status_info".

**Comment by vladmihalcea** [comment] 2023-05-28 20:47
Custom Types don't create the DB schema for you, and you should use Flyway anyway to create and manage the schema.

If it works, then you should just make sure you create the PostgreSQL schema properly for that mapping.

**Comment by vprudnikov** [comment] 2023-05-28 20:53
@vladmihalcea may this is a solution...

What is confusing me is that I have a basic property (i.e. not a collection) in another entity, and everything works fine without any Flyway script. So I guessed Hypersistence Utils somehow manages it itself.

**Comment by vprudnikov** [comment] 2023-05-28 20:59
After adding `@Type(PostgreSQLEnumType.class)` to a basic property, I got an exception. So, now I see that I should have defined an enum type before my test runs.

Regarding this issue, I see only one problem:

```
    @ElementCollection
    private PostStatus> status; <--- this works, PostgreSQLEnumType is simply not in use

    @ElementCollection
    private Set<PostStatus> statuses = new HashSet<>(); <--- this doesn't work, the contribution of the PostgreSQLEnumType leads to a problem described in the very beginning of this issue,
```

**Comment by vladmihalcea** [comment] 2023-05-30 07:23
@vprudnikov The first example is wrong:

    @ElementCollection
    private PostStatus> status;

That goes against JPA mapping specification because  you are using `@ElementCollection` on a basic type:

In the second example:

    @ElementCollection
    private Set<PostStatus> statuses = new HashSet<>();

You will have to debug Hibernate and see why the `PostgreSQLEnumType` is used instead of the default Hibernate `EnumType` since you didn't use the `@Type` annotation.

Afterward, you will need to implement the #623 issue so that you will be able to exclude the `PostgreSQLEnumType` from being auto-registered.

**Comment by vprudnikov** [comment] 2023-05-30 07:47
@vladmihalcea , sorry, you were right.
The correct example is:

```
@Enumerated(STRING)
private PostStatus status; <--- this works, PostgreSQLEnumType is simply not in use

@ElementCollection
private Set<PostStatus> statuses = new HashSet<>(); <--- this doesn't work, the contribution of the PostgreSQLEnumType leads to the error described in the very beginning of this issue,
```

**Comment by vladmihalcea** [comment] 2023-05-30 07:51
The second example also works fine, as demonstrated by [this test case](https://github.com/vladmihalcea/hypersistence-utils/blob/786f39dd4260981f36eaff048c9402b76e16aa61/hypersistence-utils-hibernate-62/src/test/java/io/hypersistence/utils/spring/repo/projection/SpringDataProjectionTest.java#L81).

That test case uses exactly the same mapping:

    @ElementCollection
    private Set<Role> roles = new HashSet<>();

And works just fine on PostgreSQL with Hibernate 6.2.

**Comment by vprudnikov** [comment] 2023-05-30 10:08
@vladmihalcea the error shows that you don't have or you didn't start Docker on your machine. If you don't have it / can't start it for whatever reason, I'll try to replicate the issue in the `SpringDataProjectionTest `test :)

**Comment by vprudnikov** [comment] 2023-05-30 10:47
@vladmihalcea I implemented a new test and it actually works in your environment! 

```
    @Test
    public void testMemberOf() {
        createAdminUser();

        List<User> users = transactionTemplate.execute(transactionStatus ->
                userRepository.findByRole(User.Role.ADMIN)
        );

        assertEquals(1, users.size());
        User user = users.get(0);
        assertEquals(1L, user.getId().longValue());
    }

    @Test
    public void testMemberOfUsingSpecification() {
        createAdminUser();

        Specification<User> spec = (root, query, builder) ->
                builder.isMember(User.Role.ADMIN, root.get("roles"));

        Optional<User> user = transactionTemplate.execute(transactionStatus -> userRepository.findOne(spec));

        assertEquals(1L, user.get().getId().longValue());
    }

    private void createAdminUser() {
        transactionTemplate.execute((TransactionCallback<Void>) transactionStatus -> {
            userRepository.persist(
                    new User()
                            .setId(1L)
                            .setFirstName("Vlad")
                            .setLastName("Mihalcea")
                            .addRole(User.Role.ADMIN)
            );

            return null;
        });
    }

```

It looks like Spring Boot 3.1 has a dependency that prevents the test from working on my side.

**Comment by vladmihalcea** [comment] 2023-05-30 10:49
I created #631 for this since the `PostgreSQLEnumType` should not be auto-registered, even if it didn't cause this issue.

**Comment by vladmihalcea** [comment] 2023-05-30 11:56
It's fixed. You just need to upgrade to 3.4.2

**Comment by vprudnikov** [comment] 2023-05-30 12:20
It is! I can confirm this.

thanks, @vladmihalcea

**Comment by vladmihalcea** [comment] 2023-05-30 12:37
I'm glad I could help
