### ISSUE TITLE
ListArrayTypeDescriptor should use Collection as the underlying JavaType

### ISSUE THREAD

**Issue by nstdio** [vladmihalcea/hypersistence-utils#650] opened 2023-08-25 13:54 UTC
**Describe the bug**
After https://github.com/hibernate/hibernate-orm/commit/fd661534d7189f6895507f75d12546dae6c4176d hibernate is not able to determine field type that is annotated with `@Type(ListArrayType.class)` and with `java.util.List` type. Hibernate 6.2.5 returns correct type but starting from Hibernate 6.2.6 returned type is `Object`.

**To Reproduce**
In order to see test failing please set Hibernate ORM version `6.2.6.Final` or above.

```java
    @Test
    public void testAttributeType() {
        doInJPA(entityManager -> {
            var eventManagedType = entityManager.getMetamodel().managedType(Event.class);
            var sensorIdsJavaType = eventManagedType.getAttribute("sensorIds").getJavaType();
            
            assertEquals(List.class, sensorIdsJavaType);
        });
    }
```

**Expected behavior**
:point_up: Test :green_circle: 

**Additional context**
Hibernate starts invoking  `ListArrayType::returnedClass` (if field type is interface) and it returns `Object.class` instead of `List.class`

**Comment by vladmihalcea** [comment] 2023-08-25 14:01
This is a Hibernate issue that can only be fixed in Hibernate. You should open a JIRA issue in Hibernate for it.

**Comment by nstdio** [comment] 2023-08-25 14:14
hm, I think it's not Hibernate issue since ` ListArrayType::returnedClass` returns `Object.class` which is not specific enough and Hibernate just uses it or do I miss something?

**Comment by vladmihalcea** [comment] 2023-08-25 14:20
If it's not a Hibernate issue, then why was it working in Hibernate 6.2.5?

**Comment by nstdio** [comment] 2023-08-25 15:19
I believe it's not that simple. Per my current understanding it was happened to work before and now after [HHH-16784](https://hibernate.atlassian.net/browse/HHH-16784) is resolved the problem with `ListArrayType` starts to rise up. What problem? I believe  `ListArrayType::returnedClass` breaks the interface contract or at least is not specific enough by returning different class then it should. 

Also note that all `AbstractArrayTypeDescriptor` subtypes return correct classes except of course `ListArrayTypeDescriptor` and why is that?

**Comment by vladmihalcea** [comment] 2023-08-25 16:07
I've just updated the `pom.xml` and run the tests with both 6.2.6 and 6.2.7, and everything works as expected.

Since there is no failing test case, it means that everything works as intended. In your case, you might be using the `JsonType` in a way that was not even intended.

> Also note that all AbstractArrayTypeDescriptor subtypes return correct classes except of course ListArrayTypeDescriptor and why is that?

Arrays are reified while I've just updated the `pom.xml` and run the tests with both 6.2.6 and 6.2.7, and everything works as expected.

Since there is no failing test case, it means that everything works as intended. In your case, you might be using the `JsonType` in a way that was not even intended.

> Also note that all AbstractArrayTypeDescriptor subtypes return correct classes except of course ListArrayTypeDescriptor and why is that?

The answer lies in the Java language specification. Arrays are reified, and generic Collections use Erasure. At runtime, the parametrized type is lost for `List`, but not for arrays.

**Comment by vladmihalcea** [comment] 2023-08-25 16:39
Fixed.

**Closed by vladmihalcea** 2023-08-25 16:39 UTC
Labels: enhancement

**Comment by vladmihalcea** [comment] 2023-08-25 19:25
@nstdio The 3.5.2 version switches to using `Collection` for the `ListArrayTypeDescriptor`. 

On Hibernate 6.2, `getJavaType()` will return `Collection`, and that might work for your use case. If it doesn't, then maybe [HHH-16784](https://hibernate.atlassian.net/browse/HHH-16784) will make that return `List`, as it does on Hibernate 6.1.

**Comment by nstdio** [comment] 2023-08-25 23:52
Many thanks for your time and for reopening the issue :+1: 

> Since there is no failing test case, it means that everything works as intended. In your case, you might be using the JsonType in a way that was not even intended.

If there is no failing tests that could also indicate missing test. For instance test case mentioned in this issue. Okay,  anyways. FYI I'm not using `JsonType`.

> The answer lies in the Java language specification. Arrays are reified, and generic Collections use Erasure. At runtime, the parametrized type is lost for List, but not for arrays.

That was a rhetorical question to shed light on a problem for you. Obviously, `ListArrayTypeDescriptor` potentially returns `Collection` and `Object[]`. Now I see `Object[]` part removed.

Perhaps it's counterintuitive to have `ListArrayTypeDescriptor` which in fact deals with `Collection` despite that the name suggests otherwise. Shouldn't it named `CollectionArrayTypeDescriptor`?
