### ISSUE TITLE
[hypersistence-63 V.7.3.2] org.hibernate.type.SqlTypes code: 1111

### ISSUE THREAD

**Issue by RomuDeuxfois** [vladmihalcea/hypersistence-utils#701] opened 2024-02-16 10:27 UTC
**Describe the bug**
I have a java class with a array type property

```
  @Type(StringArrayType.class)
  @Column(name = "endpoint_ips")
  private String[] ips;
```

Everything works fine with hypersistence-utils-hibernate-63 version 3.7.0.
But when I try to run my app with the version 3.7.2 I have this error :

```
Unable to determine SQL type name for column 'endpoint_ips' of table 'assets': No type mapping for org.hibernate.type.SqlTypes code: 1111 (OTHER)
```

**To Reproduce**

Have a java class with an array type, I think it's enough.

**Expected behavior**

No error.

**Comment by yasin-herken** [comment] 2024-02-16 12:33
You can look into https://hibernate.atlassian.net/browse/HHH-17588.

**Comment by vladmihalcea** [comment] 2024-02-16 13:28
@RomuDeuxfois Because of the [HHH-17588](https://hibernate.atlassian.net/browse/HHH-17588) issue, the `ArrayType` uses the OTHERS JDBC TYpes, as the ARRAY one will not work at all with Hibernate 6.4. 

However, [all the array tests](https://github.com/vladmihalcea/hypersistence-utils/tree/master/hypersistence-utils-hibernate-63/src/test/java/io/hypersistence/utils/hibernate/type/array) work just fine with Hibernate 6.4, so you can use those as a reference of what could be done. If you have a distinct use case that's not covered by the current test cases, then you should provide a replicating test case for it.

**Comment by RomuDeuxfois** [comment] 2024-02-16 13:35
Thank you very much for your quick responses.
I will come back to you after testing.

**Comment by RomuDeuxfois** [comment] 2024-02-19 08:00
I followed your test example

```
  @Type(StringArrayType.class)
  @Column(name = "endpoint_ips", columnDefinition = "text[]")
  private String[] ips;
```

But it appears that the DB schema is created manually in SQL before hibernate (with flyway).
Which results in a type mismatch :

Schema-validation: wrong column type encountered in column [endpoint_ips] in table [assets]; found [_text (Types#ARRAY)], but expecting [text[] (Types#OTHER)]

![image](https://github.com/vladmihalcea/hypersistence-utils/assets/53513584/e21a2b48-8c04-4e41-9ca4-08d199d38f8b)

**Comment by vladmihalcea** [comment] 2024-02-19 08:22
Then, this issue is a duplicate of #697. Check out that issue for more details about how you can work around it.

**Closed** 2024-02-19 08:23 UTC
Labels: requires test case
