### ISSUE TITLE
Expecting BasicPluralJavaType for array class `[Ljava.util.UUID;`, but got `com.vladmihalcea.hibernate.type.array.internal.UUIDArrayTypeDescriptor error with Hibernate 6.4

### ISSUE THREAD

**Issue by fkjaekel** [vladmihalcea/hypersistence-utils#698] opened 2024-02-02 15:10 UTC
I upgraded to 3.7.1 to check hibernate 6.4 support, but I'm still getting this exception:

```
 java.lang.IllegalArgumentException: Expecting BasicPluralJavaType for array class `[Ljava.util.UUID;`, but got `com.vladmihalcea.hibernate.type.array.internal.UUIDArrayTypeDescriptor@6c081af`
	at org.hibernate.loader.ast.internal.MultiKeyLoadHelper.resolveArrayJdbcMapping(MultiKeyLoadHelper.java:46) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.loader.ast.internal.MultiIdEntityLoaderArrayParam.<init>(MultiIdEntityLoaderArrayParam.java:58) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.buildMultiIdLoader(AbstractEntityPersister.java:892) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.prepareLoaders(AbstractEntityPersister.java:3419) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:206) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.internal.SessionFactoryImpl.initializeMappingModel(SessionFactoryImpl.java:364) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:293) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:450) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1507) ~[hibernate-core-6.4.2.Final.jar:6.4.2.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:75) ~[spring-orm-6.1.3.jar:6.1.3]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[spring-orm-6.1.3.jar:6.1.3]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-6.1.3.jar:6.1.3]
	... 23 common frames omitted
```

**Comment by vladmihalcea** [comment] 2024-02-03 08:57
@fkjaekel Try to provide a replicating test case in this repository, as all integration tests run just fine in this repository.

**Comment by rolandkreuzer** [comment] 2024-02-08 13:33
I ran into the Stacktrace described in #697 (which was marked duplicate of this Issue) in combination with Spring Boot 3.2.2 / Spring Data JPA 3.2.2 and hypersistence-utils-hibernate-63:3.7.1 on the Postgres dialect.

It looks as for some reason Hibernate applied the UUIDArrayType to bind the ID list argument passed into 
_org.springframework.data.repository.ListCrudRepository.findAllById(Iterable<ID>)_
when ID was of type UUID.
This then fails as VarbinaryJdbcType tries to cast from UUID[] to byte[]

No idea whether this library, Hibernate or Spring Data is at fault here.

Disabling the automatic types contribution (as suggested in a previous comment) helped to avoid the issue for me.
In case someone else needs it: it can also be done via JPA properties in Spring Config like

```
spring:
  jpa:
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
```

**Comment by vladmihalcea** [comment] 2024-02-08 14:38
@rolandkreuzer Thanks for confirming that the issue is caused by the `TypeContributors`. I will disable it by default in `hypersistence-utils-hibernate-63` and release a new version.

**Comment by vladmihalcea** [comment] 2024-02-08 14:58
Fixed.

**Closed by vladmihalcea** 2024-02-08 14:58 UTC
Labels: bug

**Comment by emeraldhieu** [comment] 2024-02-15 04:52
Hello, I still got the error.

```
Caused by: java.lang.IllegalArgumentException: Expecting BasicPluralJavaType for array class `[Ljava.lang.String;`, but got `com.vladmihalcea.hibernate.type.array.internal.StringArrayTypeDescriptor@1eb49f06`
	at org.hibernate.loader.ast.internal.MultiKeyLoadHelper.resolveArrayJdbcMapping(MultiKeyLoadHelper.java:46)
	at org.hibernate.loader.ast.internal.MultiIdEntityLoaderArrayParam.<init>(MultiIdEntityLoaderArrayParam.java:58)
	at org.hibernate.persister.entity.AbstractEntityPersister.buildMultiIdLoader(AbstractEntityPersister.java:892)

```

with this Gradle config
```
    implementation("com.vladmihalcea:hibernate-types-60:2.21.1")
    implementation("io.hypersistence:hypersistence-utils-hibernate-63:3.7.2")
```

**Comment by vladmihalcea** [comment] 2024-02-15 05:03
Remove everything that starts with `com.vladmihalcea` and try again:
 `implementation("com.vladmihalcea:hibernate-types-60:2.21.1")`

Why are you still using that old dependency that's no longer needed?

**Comment by emeraldhieu** [comment] 2024-02-15 05:19
@vladmihalcea IT WORKS! Thanks a lot!

**Comment by sivaj-241** [comment] 2024-03-29 12:48
Hi I am using  <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-60</artifactId>
            <version>2.21.1</version> 
            But still I am getting below issue:
            by: java.lang.IllegalArgumentException: Expecting BasicPluralJavaType for array class `[Ljava.util.UUID;`, but got `com.vladmihalcea.hibernate.type.array.internal.UUIDArrayTypeDescriptor@65262308`

**Comment by vladmihalcea** [comment] 2024-03-29 13:23
@sivaj-241 You need to [migrate to Hypersistence Utils](https://github.com/vladmihalcea/hypersistence-utils?tab=readme-ov-file#migrating-to-version-3). There is no `hibernate-types` project anymore.
